### ISSUE TITLE
WCRFT2 tool checks https while it should be http

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/monitoring#8]
https://github.com/clarin-eric/monitoring/blob/master/conf.d/switchboard-tool-registry.conf#L1028 seems to check https://nlp.pwr.wroc.pl/redmine/projects/wcrft/wiki/ while the [JSON](https://github.com/clarin-eric/switchboard-tool-registry/blob/master/WCRFT2.json) in the switchboard tool registry uses the http version:
http://nlp.pwr.wroc.pl/redmine/projects/wcrft/wiki/

**Comment by jnphilipp** [comment]
In the switchboard JSON are two urls:
* https://github.com/clarin-eric/switchboard-tool-registry/blob/master/WCRFT2.json#L7
* https://github.com/clarin-eric/switchboard-tool-registry/blob/master/WCRFT2.json#L36

One is http the other is https and both get checked and for the https the ssl cert gets also checked.
This is the same in all switchboard tools.

**Comment by dietervu** [comment]
The second one is OK
https://monitoring.clarin.eu/monitoring/list/services?(service=%2AWCRFT2%2A|service_display_name=%2AWCRFT2%2A)#!/monitoring/service/show?host=WCRFT2&service=WCRFT2

but the first one is still incorrectly checking the https link while it should be http, isn't it?
https://monitoring.clarin.eu/monitoring/list/services?service_state=2&service_handled=0&host=WCRFT2#!/monitoring/service/show?host=WCRFT2&service=ssl_cert%20nlp.pwr.wroc.pl

**Comment by jnphilipp** [comment]
There was a n error in the ssl cert check generation for the second url.

**Comment by andmor-** [comment]
@jnphilipp we are not sure we understand your comment. 
Can you confirm that the problem you fixed was with:
https://monitoring.clarin.eu/monitoring/list/services?service_state=2&service_handled=0&host=WCRFT2#!/monitoring/service/show?host=WCRFT2&service=ssl_cert%20nlp.pwr.wroc.pl

which now disappeared due to the fix.

I assume [this commit](https://github.com/clarin-eric/monitoring/commit/81551fe11e5a06c6a8fd3280cbe932c5cb74b73e) fixes it. 
i.e. before this, the host address (derived from `homepage`) was mistakenly being used also when generating the checks configuration for the service URL (instead of deriving it from `url`). Can you confirm?

(if this is the case, are we aware if this affected any other checks? like: https://github.com/clarin-eric/switchboard-tool-registry/blob/master/UDPipe.json)

**Comment by jnphilipp** [comment]
In short yes and only `WCRFT2` was affected.

With some context: each JSON-file has two URLs: `homepage` and `url`. Both will be check, `homepage` over the host check and `url` as a service. If one or both of them start with `https` a ssl check will be generated, two if the domains differ. So what happend bevor [81551fe](https://github.com/clarin-eric/monitoring/commit/81551fe11e5a06c6a8fd3280cbe932c5cb74b73e) was that if the ssl check should be generated for `url` the CN of the certificate was check against that of `homepage` instead.

As far as I'm aware of `WCRFT2` was the only one affected.

**Comment by andmor-** [comment]
OK that explains it. From what you wrote, I do  believe that [UDpipe](https://github.com/clarin-eric/switchboard-tool-registry/blob/master/UDPipe.json) was under the same conditions (*). But it is all fixed now and in fact we had no reports from other than `WCRFT2`.


\* `url` starts with `https` so and ssl check should be generated for `url`, but the `CN` in `homepage` is different

**Comment by andmor-** [comment]
Thank you for clarifying!
